{
  description = "Aero-tot27: Minimal Barebones NixOS for Niri";

  inputs = {
    # Core NixOS repository (Tracking version 26.05)
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
  };

  outputs = { self, nixpkgs }: {
    nixosConfigurations = {
      # "nixos" is the hostname. This must match the hostName in configuration.nix
      nixos = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          # Hardware specific configurations (Generated by NixOS installer)
          ./hardware-configuration.nix
          
          # Main system configuration
          ./configuration.nix
        ];
      };
    };
  };
}
